FROM python:3.10-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PORT=8000

WORKDIR /app

COPY requirements-proxy.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/minimal.py ./app/minimal.py

CMD gunicorn -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:${PORT} app.minimal:app